
#默认端口
#server:
#  port: 9091
---
#默认端口环境
spring:
  profiles:
    active: dev
#  config:
#    location: F:\defaultbrowerdownload\application.yml
#我们能配置的属性都来源ServerProperties这个属性文件
server:
  servlet:
    context-path: /boot
  undertow:
    url-charset: UTF-8
#debug: true  #debug模式，查看容器中激活了哪些组件

#logging:
#  config: classpath:logback-spring.xml
#  level: trace     #设置日志级别
#  file:           #不指定路径在当前项目下生成日志文件，指定路径，按照路径输出
#    path: ./logs      #在当前磁盘的根路径下创建spring文件夹和log文件夹，使用spring.log作为默认的日志文件
#  pattern:
#    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'    #控制台输出的日志格式
#    file: '%d{yyyy-MM-dd} === [%thread] ===  %-5level %logger{50} - %msg%n'   #指定文件输出的日志格式
---

server:
  port: 8081
spring:
  profiles: dev
---

server:
  port: 8082
spring:
  profiles: prod
---
#配置person
#person:
#  username: 黄信胜
#  age: 23
#  boss: false
#  birth: 1998/08/25
#  lists:
#    - tom
#    - jie
#  maps:
#    k1: v1
#    k2: 23
#  dog:
#    dogName: jerry


