
#默认端口
server:
  port: 9090

#默认端口环境
spring:
  profiles:
    active: dev

#配置person
person:
  username: 黄信胜
  age: 23
  boss: false
  birth: 1998/08/25
  lists:
    - tom
    - jie
  maps:
    k1: v1
    k2: 23
  dog:
    dogName: jerry


